<?php

/**
 * Custom Related Products by Category
 * @author : Tabish Naeem <[<t.naeem@live.com>]>
 */
$imageHelper = $this->helper('Tabish\RelatedProductByCategories\Helper\Image'); 
$items = $block->getCurrentCategoryProducts();
$blockId = 'products-'.rand().time();
?>

<?php if( null != $items && count( $items ) > 0 ) : ?>
<div class="container custom-related-products-by-category">
    <div class="product related-product">
        <div class="product-filter">
            <h3>Related Products</h3>
        </div>
        <div class="related-product-slider custom-dots <?php echo $blockId; ?>">
            <?php foreach( $items as $product ) : ?>
                <div class="related-product-slider_item">
                    <?php $_image = $imageHelper->getImg($product, 300, 300, 'category_page_grid'); ?>
                    <?php if( $_image ) : ?>
                        <div class="related-product-sliderproduct">
                            <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $_image->getLabel() ?>" class="product-item-photo">
                                <img src="<?php echo $_image->getUrl(); ?>" alt="<?php echo $_image->getLabel() ?>" />
                            </a>
                        </div>
                        <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $product->getName() ?>" href="<?php /* @escapeNotVerified */ echo $product->getProductUrl() ?>">
                            <?php echo $product->getName() ?></a>
                        </strong>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<?php else: ?>
<div class="container custom-related-products-by-category">
	<div class="product related-product">
		<div class="product-filter">
    		<h3>No Related Products</h3>
		</div>
		<div class="related-product-slider custom-dots">
		</div>
	</div>
</div>
<?php endif; ?>

<script type="text/javascript">
    require([
        "jquery",
        "js/custom/slick.min"
    ], function($){

            $('.<?php echo $blockId; ?>').slick({
                slidesToShow: 6,
                slidesToScroll: 1,
                autoplay: true,
                dots: false,
                lazyLoad: 'ondemand',
                nextArrow: '<span class="nav-next"><i class="fas fa-chevron-right"></i></span>',
                prevArrow: '<span class="nav-prev"><i class="fas fa-chevron-left"></i></span>',
                autoplaySpeed: 2000,
                responsive: [
                    {
                        breakpoint: 767,
                        settings: {
                            slidesToShow: 1,
                            slidesToScroll: 1,
                            dots: false,
                            arrows: false
                        }
                    },
                    {
                        breakpoint: 991,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 2,
                        }
                    }
                ]
            });
    });
</script>